### ISSUE TITLE
README-commit link error

### ISSUE THREAD

**Issue by littlefish0331** [Sea-n/nctu-timetable#1]
hi~
it's really a nice crawler example for me to learn shell script.
and i find that your repo readme has a simple error about commit link

the right commit link is 'https://github.com/Sea-n/nctu-timetable/commits/master'
you can fix that.

happy coding!

**Comment by Sea-n** [comment]
Thanks for letting me know about this error!

Would you like to make a Pull Request?  
It's [Hacktoberfest](https://hacktoberfest.digitalocean.com/) this month, you could get a T-Shirt if submitted 4 PR. 🙃

**Comment by littlefish0331** [comment]
got it.
Thank you for telling me this activity
I just pull a request and u can check that.
